# Cómo trabajar con matrices

In [1]:
import tensorflow as tf

In [2]:
session = tf.Session()

## 1. Cómo crear matrices

In [25]:
identity = tf.diag([1.,1.,1.,1.]) # Matriz identidad 4x4 (float)
print(session.run(identity))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
A = tf.truncated_normal([3,4]) # Datos de una distribución normal truncada
print(session.run(A))

[[ 0.783186    0.09416551 -1.2356915   1.0723972 ]
 [-0.6733717   0.05445028 -0.51133263 -0.87277794]
 [ 1.874962   -0.3335352   0.31495884 -0.034371  ]]


In [18]:
B = tf.fill([3,4], 1995.)
print(session.run(B))

[[1995. 1995. 1995. 1995.]
 [1995. 1995. 1995. 1995.]
 [1995. 1995. 1995. 1995.]]


In [12]:
C = tf.random_uniform([4,3])
print(session.run(C))

[[0.12889326 0.07850671 0.04429281]
 [0.4162767  0.4645064  0.4644382 ]
 [0.70621884 0.9182581  0.3417455 ]
 [0.5348877  0.2727493  0.3545742 ]]


In [9]:
import numpy as np
data = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
D = tf.convert_to_tensor(data)
print(session.run(D))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 2. Operar con matrices

In [21]:
print(session.run(A+B))

[[1995.6337 1994.5581 1994.6938 1995.9583]
 [1994.4791 1995.8461 1996.0643 1995.1958]
 [1994.1786 1995.6941 1996.0546 1994.1815]]


In [22]:
print(session.run(B-B))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
print(session.run(tf.matmul(A,C))) # Producto matricial

[[ 0.73582095  1.4669106   0.72287774]
 [ 1.3064486   1.2984933   2.1319528 ]
 [-1.7027698  -0.6130451  -1.4166672 ]]


In [26]:
print(session.run(tf.matmul(A,identity)))

[[-0.42138216 -1.3760359  -0.857155   -0.0296778 ]
 [ 0.78601974  1.0974598  -0.65564007 -0.00521921]
 [ 0.16446623  1.0771966  -1.7751687  -0.11794449]]


## 3. Traspuesta y determinante --> Inversa

In [28]:
print(session.run(tf.transpose(A))) # Traspuesta de A

[[-0.3531443   0.11395104 -0.44381917]
 [ 0.248513    0.18646722 -0.7873152 ]
 [-0.26095486 -1.2628871   1.3296496 ]
 [ 0.8967517  -1.357636   -1.7988157 ]]


In [29]:
print(session.run(tf.matrix_determinant(D))) # Determinante de D--> La matriz debe ser cuadrada (m = n)

6.66133814775094e-16


In [30]:
E = tf.convert_to_tensor(np.array([[1.,2.,3.],[-3.,-6.,-1.],[0.,5.,-3.,]]))
print(session.run(tf.matrix_determinant(E)))

-40.0


In [32]:
print(session.run(tf.matrix_inverse(D))) # Matriz singular --> no tiene inversa

[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


In [37]:
E_inverse = session.run(tf.matrix_inverse(E)) # Inversa de E
print(E_inverse)

[[-0.575 -0.525 -0.4  ]
 [ 0.225  0.075  0.2  ]
 [ 0.375  0.125  0.   ]]


In [38]:
print(session.run(tf.matmul(E, E_inverse))) # Matriz identidad

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.55111512e-17  1.00000000e+00]]


## 4. Descomposición

In [40]:
print(session.run(tf.cholesky(identity))) # Para matrices simétricas y definidas positivas

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 5. Valores y vectores propios

In [41]:
print(session.run(tf.self_adjoint_eigvals(E))) # Valores propios de la matriz E

[-10.24888536  -0.66882335   2.91770871]


In [42]:
print(session.run(tf.self_adjoint_eig(E))) # Valores propios & vectores propios de la matriz E

(array([-10.24888536,  -0.66882335,   2.91770871]), array([[ 0.21442787,  0.60489799, -0.76688924],
       [ 0.80402486,  0.3364893 ,  0.49022339],
       [-0.55458517,  0.72171557,  0.41420034]]))
