# Redes neuronales multicapas

### Ejemplo 1D 

In [1]:
import tensorflow as tf
import numpy as np
session = tf.Session()

In [3]:
data_size = 25
data_1d = np.random.normal(size = data_size)
x_input_1d = tf.placeholder(shape=[data_size], dtype=tf.float32)

In [6]:
def conv_layer_1d(input_1d, my_filter):
    input_2d = tf.expand_dims(input_1d, 0)
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    convolution = tf.nn.conv2d(input_4d, filter = my_filter, strides = [1,1,1,1], padding="VALID")
    output = tf.squeeze(convolution)
    return(output)

In [7]:
my_filter = tf.Variable(tf.random_normal(shape=[1,5,1,1]))
my_conv_output = conv_layer_1d(x_input_1d, my_filter)

In [8]:
def activation(input_1d):
    return tf.nn.relu(input_1d)
my_activation_output = activation(my_conv_output)

In [9]:
def max_pool(input_1d, width):
    input_2d = tf.expand_dims(input_1d, 0)
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    pooling = tf.nn.max_pool(input_4d, ksize=[1,1,width,1], strides=[1,1,1,1], padding="VALID")
    output = tf.squeeze(pooling)
    return(output)

In [10]:
my_maxpool_ouput = max_pool(my_activation_output, width=5)

In [11]:
def fully_connected(input_layer, num_output):
    weight_shape = tf.squeeze(tf.stack([tf.shape(input_layer), [num_output]]))
    weight = tf.random_normal(weight_shape, stddev=0.1)
    bias = tf.random_normal(shape=[num_output])
    input_layer_2d = tf.expand_dims(input_layer,0)
    full_output = tf.add(tf.matmul(input_layer_2d, weight), bias)
    full_output_1d = tf.squeeze(full_output)
    return(full_output_1d)

In [12]:
my_full_output = fully_connected(my_maxpool_ouput, 5)

In [13]:
init = tf.global_variables_initializer()
session.run(init)

In [14]:
feed_dict = {x_input_1d: data_1d}

In [16]:
data_1d

array([ 1.11726143,  1.2199282 ,  2.08403659, -0.5641956 , -1.97417837,
        0.74121749, -0.06573571,  0.68324515,  0.15140036, -1.47523627,
       -1.76683959,  0.29992843, -0.40987229, -2.27857269,  0.85453741,
        0.90486784, -0.83307896,  0.86211523, -0.72954449, -2.11379079,
        1.17546086, -1.09596305,  1.80804086, -0.27225049,  1.95735632])

In [17]:
session.run(my_filter)

array([[[[ 0.21220557]],

        [[-0.8410326 ]],

        [[-0.4553594 ]],

        [[ 1.3882189 ]],

        [[ 1.3427733 ]]]], dtype=float32)

In [15]:
# Operación de convolución
print("Input: tamaño 25, Operación: convolución con filtro de tamaño 5 + stride de tamaño 1, Resultado: tamaño 21")
print(session.run(my_conv_output, feed_dict=feed_dict))

Input: tamaño 25, Operación: convolución con filtro de tamaño 5 + stride de tamaño 1, Resultado: tamaño 21
[-5.171997   -2.9822598   2.7564158   2.0292904   0.13940382 -1.8692768
 -5.0779386  -1.360606    1.9433976  -2.592258   -2.4562511   3.8472493
  1.5777737  -1.6131305   0.01685643 -3.3510168  -1.9256727   1.9192178
  1.9940488   1.2062836   2.5982141 ]


In [18]:
# Función de activación
print("Input: tamaño 21, Operación: ReLU al array anterior, Resultado: tamaño 21")
print(session.run(my_activation_output, feed_dict=feed_dict))

Input: tamaño 21, Operación: ReLU al array anterior, Resultado: tamaño 21
[0.         0.         2.7564158  2.0292904  0.13940382 0.
 0.         0.         1.9433976  0.         0.         3.8472493
 1.5777737  0.         0.01685643 0.         0.         1.9192178
 1.9940488  1.2062836  2.5982141 ]


In [19]:
# Operción de Max Pooling
print("Input: tamaño 21, Operación: maxpooling con ventana de tamaño 5 + stride de tamaño 1, Resultado: tamaño 17")
print(session.run(my_maxpool_ouput, feed_dict=feed_dict))

Input: tamaño 21, Operación: maxpooling con ventana de tamaño 5 + stride de tamaño 1, Resultado: tamaño 17
[2.7564158 2.7564158 2.7564158 2.0292904 1.9433976 1.9433976 1.9433976
 3.8472493 3.8472493 3.8472493 3.8472493 3.8472493 1.5777737 1.9192178
 1.9940488 1.9940488 2.5982141]


In [20]:
# Capa Totalmente Conectada
print("Input: tamaño 17, Operación de conectar totalmente la entrada con 5 valores de salida, Resultado: tamaño 5")
print(session.run(my_full_output, feed_dict=feed_dict))

Input: tamaño 17, Operación de conectar totalmente la entrada con 5 valores de salida, Resultado: tamaño 5
[-0.36904252  0.5647052  -1.968683   -0.60227275 -0.5455638 ]


### Ejemplo 2D

In [21]:
session = tf.Session()

In [2]:
data_size = [10,10]
data_2d = np.random.normal(size = data_size)
x_input_2d = tf.placeholder(dtype=tf.float32, shape=data_size)

In [3]:
def conv_layer_2d(input_2d, my_filter):
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    convolution = tf.nn.conv2d(input_4d, filter=my_filter, strides = [1,2,2,1], padding="VALID")
    output = tf.squeeze(convolution)
    return(output)

In [4]:
my_filter = tf.Variable(tf.random_normal(shape=[2,2,1,1]))
my_conv_output = conv_layer_2d(x_input_2d, my_filter)

Instructions for updating:
Colocations handled automatically by placer.


In [5]:
def activation(input_2d):
    return(tf.nn.relu(input_2d))

In [6]:
my_activation_output = activation(my_conv_output)

In [7]:
def max_pool(input_2d, width, height):
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    pooling = tf.nn.max_pool(input_4d, ksize=[1,height,width,1], strides=[1,1,1,1], padding="VALID")
    output = tf.squeeze(pooling)
    return(output)

In [8]:
my_maxpool_ouput = max_pool(my_activation_output, width=2, height=2)

In [9]:
def fully_connected(input_layer, num_output):
    flat_input = tf.reshape(input_layer, [-1])
    weight_shape = tf.squeeze(tf.stack([tf.shape(flat_input), [num_output]]))
    weight = tf.random_normal(weight_shape, stddev=0.1)
    bias = tf.random_normal(shape=[num_output])
    input_layer_2d = tf.expand_dims(flat_input,0)
    full_output = tf.add(tf.matmul(input_layer_2d, weight), bias)
    full_output_1d = tf.squeeze(full_output)
    return(full_output_1d)

In [10]:
my_full_output = fully_connected(my_maxpool_ouput, 5)

In [11]:
init = tf.global_variables_initializer()
session.run(init)

In [12]:
feed_dict = {x_input_2d: data_2d}

In [13]:
data_2d

array([[ 0.74753444,  0.52570125,  1.04673704,  1.61849144,  0.65738728,
        -0.83132498, -0.25544721,  1.01432842, -1.09470176, -0.61123368],
       [ 0.18801717, -1.38822876,  0.8578837 ,  1.94846553, -1.0083942 ,
        -0.56553706,  0.15651851,  0.70291468, -0.79874547, -0.77450513],
       [ 1.02241441,  1.3242069 ,  1.26333557, -0.87276736, -0.43397919,
         0.93264351, -0.08248914,  0.23599122,  0.3359301 ,  0.47229976],
       [-1.62388294, -0.64885824, -0.31847561, -0.37966508, -1.01734346,
         0.6018221 ,  0.65038121, -1.39891275, -0.24269532,  0.12905426],
       [-0.22607312,  0.10693471, -1.62813553, -0.58142566,  1.00355023,
        -2.48416283, -1.21616063,  0.78630272,  0.44928593, -1.05417865],
       [-0.60273489, -2.21954273, -0.12081587,  1.33581785,  0.61076213,
        -2.17895837, -0.1423508 ,  1.12724211, -0.68649584, -1.22947961],
       [-0.37313561,  0.23129354, -0.75677607, -0.44862031, -0.58920591,
        -0.40071974, -1.4216906 ,  0.46273198

In [14]:
session.run(my_filter)

array([[[[-0.5660564]],

        [[-1.0568304]]],


       [[[ 1.4668087]],

        [[ 0.298678 ]]]], dtype=float32)

In [15]:
# Operación de convolución
print("Input: tamaño 10x10, Operación: convolución con filtro de tamaño 2x2 + stride de tamaño 2x2, Resultado: tamaño 5x5")
print(session.run(my_conv_output, feed_dict=feed_dict))

Input: tamaño 10x10, Operación: convolución con filtro de tamaño 2x2 + stride de tamaño 2x2, Resultado: tamaño 5x5
[[-1.1175718  -0.46266812 -1.1415837  -0.48784786 -0.13730127]
 [-4.5539317  -0.37329245 -2.0524864   0.33345115 -1.0067381 ]
 [-1.5320671   1.7578504   2.302337   -0.01469213 -0.5144097 ]
 [ 1.0669879   3.1495733   2.1024795   1.550785    1.1412563 ]
 [ 3.1332695   2.0577922   0.4474544  -0.03526282  2.6365595 ]]


In [16]:
# Función de activación
print("Input: tamaño 5x5, Operación: ReLU al array anterior, Resultado: tamaño 5x5")
print(session.run(my_activation_output, feed_dict=feed_dict))

Input: tamaño 5x5, Operación: ReLU al array anterior, Resultado: tamaño 5x5
[[0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.33345115 0.        ]
 [0.         1.7578504  2.302337   0.         0.        ]
 [1.0669879  3.1495733  2.1024795  1.550785   1.1412563 ]
 [3.1332695  2.0577922  0.4474544  0.         2.6365595 ]]


In [17]:
# Operción de Max Pooling
print("Input: tamaño 5x5, Operación: maxpooling con ventana de tamaño 2x2 + stride de tamaño 1, Resultado: tamaño 4x4")
print(session.run(my_maxpool_ouput, feed_dict=feed_dict))

Input: tamaño 5x5, Operación: maxpooling con ventana de tamaño 2x2 + stride de tamaño 1, Resultado: tamaño 4x4
[[0.         0.         0.33345115 0.33345115]
 [1.7578504  2.302337   2.302337   0.33345115]
 [3.1495733  3.1495733  2.302337   1.550785  ]
 [3.1495733  3.1495733  2.1024795  2.6365595 ]]


In [18]:
# Capa Totalmente Conectada
print("Input: tamaño 4x4, Operación de conectar totalmente la entrada con 5 valores de salida, Resultado: tamaño 5")
print(session.run(my_full_output, feed_dict=feed_dict))

Input: tamaño 4x4, Operación de conectar totalmente la entrada con 5 valores de salida, Resultado: tamaño 5
[-1.8519917   2.891757   -2.5081668   0.34134793  2.3489718 ]
